#!/bin/sh

set -e

if [ $? -ne 2 ]
then
	echo "Usage: wiomw-start <USERNAME> <PASSHASH>" >&2
	false
fi

USERNAME="$1"
PASSHASH="$2"

SCP_HOME="/jffs/etc"
SCP_SERVER="scp.whoisonmywifi.net"
SCP_USER="anon"
SCP_PASS="wiomw"
UNAME="`uname -srvmpi`"

if [ ! -d /jffs/etc ]
then
	mkdir /jffs/etc
fi

if [ ! -e /jffs/etc/wiomw.conf ]
then
	cd /jffs/etc
	HOME=$SCP_HOME DROPBEAR_PASSWORD=$SCP_PASS scp $SCP_USER@$SCP_SERVER:wiomw.conf.example .
	mv wiomw.conf.example wiomw.conf
	sed -i -e "s/^\(\s*USERNAME\s*=\s*\)$/\1$USERNAME/" wiomw.conf
	sed -i -e "s/^\(\s*PASSHASH\s*=\s*\)$/\1$PASSHASH/" wiomw.conf
	chmod 400 wiomw.conf
	cd -
fi

if [ ! -e /jffs/etc/wiomw-ca.crt ]
then
	cd /jffs/etc
	HOME=$SCP_HOME DROPBEAR_PASSWORD=$SCP_PASS scp $SCP_USER@$SCP_SERVER:/wiomw-ca.crt .
	chmod 400 wiomw-ca.crt
	cd -
fi

if [ ! -d /tmp/var/wwwext ]
then
	mkdir /tmp/var/wwwext
fi

if [ ! -d /jffs/sbin ]
then
	mkdir /jffs/sbin
fi

if [ ! -x /jffs/sbin/wiomw-plugin ]
then
	cd /jffs/sbin
	HOME+$SCP_HOME DROPBEAR_PASSWORD=$SCP_PASS scp $SCP_USER@$SCP_SERVER:/plugin/$UNAME/wiomw-plugin-$VERSION .
	chmod 500 wiomw-plugin
	cd -
fi

/jffs/sbin/wiomw-plugin 2> /tmp/var/wwwext/wiomw.log &

